"""rename department

Revision ID: 433b5af13f78
Revises: 0cceda9585b0
Create Date: 2024-10-01 18:35:40.044702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433b5af13f78'
down_revision = '0cceda9585b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###